version: '3.4'

services:
  ShoppingList.DB:
    container_name: ShoppingList.DB
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=secretPassword  
        - POSTGRES_DB=ShoppingListDB
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_shopping:/var/lib/postgresql/data/

  ShoppingList.API:
    container_name: ShoppingList.API
    depends_on:
      - ShoppingList.DB
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ShoppingList.DB;Database=ShoppingListDB;Username=admin;Password=secretPassword
    ports:
      - "8003:8080"
      - "8083:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  Identity.DB:
    container_name: Identity.DB
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=secretPassword  
        - POSTGRES_DB=IdentityDB
    restart: always
    ports:
        - "5433:5432"
    volumes:
        - postgres_identity:/var/lib/postgresql/data/

  ShoppingList.Identity:
    container_name: ShoppingList.Identity
    depends_on:
      - Identity.DB
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=Identity.DB;Database=IdentityDB;Username=admin;Password=secretPassword
      - Apis__WebApp=https://localhost:8081
    ports:
      - "8002:8080"
      - "8082:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ShoppingList.Bff:
    container_name: ShoppingList.Bff
    depends_on:
      - ShoppingList.Identity
      - ShoppingList.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Apis__Data=https://ShoppingList.API:8081
      - Apis__Identity=https://ShoppingList.Identity:8081
    ports:
      - "8001:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
