version: '3.4'

services:
  ShoppingList.DB:
    image: postgres

  ShoppingList.API:
    image: ${DOCKER_REGISTRY-}shoppinglistapi
    build:
      context: .
      dockerfile: ShoppingList.Api/Dockerfile

  Identity.DB:
    image: postgres

  ShoppingList.Identity:
    image: ${DOCKER_REGISTRY-}shoppinglistidentity
    build:
      context: .
      dockerfile: ShoppingList.Identity/Dockerfile

  ShoppingList.Bff:
    image: ${DOCKER_REGISTRY-}shoppinglistbff
    build:
      context: .
      dockerfile: ShoppingList.Bff/Dockerfile

volumes:
  postgres_shopping:
  postgres_identity:


